// apps/client2/src/components/FormButton.vue
<script setup lang="ts">
import SpinnerIcon from "~icons/gg/spinner";
interface IFormButton {
  type: string;
  loading?: boolean;
}

const props = defineProps<IFormButton>();
</script>

<template>
  <button
    class="
      w-full
      bg-gray-600
      hover:(bg-gray-500)
      px-6
      py-6
      text-white
      transition-all
      text-md
      flex
      justify-center
      items-center
      rounded-full
    "
  >
    <spinner-icon v-if="loading" class="animate-spin" />
    <slot v-else />
  </button>
</template>

// apps/client/src/components/FormButton.tsx
import React from "react";
import tw, { styled, css } from "twin.macro";
import { CgSpinner as SpinnerIcon } from "react-icons/cg";

interface IFormButton {
  children?: React.ReactNode;
  isLoading?: boolean;
  leftIcon?: React.ReactElement;
  text?: string;
  backgroundColor?: string;
}

export const FormButton: React.FC<IFormButton> = (props) => (
  <button
    css={tw`flex justify-center text-white font-bold items-center h-auto w-full h-2 bg-purple-600 pl-10 pr-10 pt-6 pb-6 rounded-lg hover:bg-purple-500`}
  >
    {props.isLoading ? (
      <div css={tw`animate-spin`}>
        <SpinnerIcon size="30px" />
      </div>
    ) : (
      props.text
    )}
  </button>
);
