// apps/client/src/components/FormButton.tsx
import React from "react";
import tw, { styled, css } from "twin.macro";
import { CgSpinner as SpinnerIcon } from "react-icons/cg";

interface IFormButton {
  children?: React.ReactNode;
  isLoading?: boolean;
  leftIcon?: React.ReactElement;
  text?: string;
  backgroundColor?: string;
}

export const FormButton: React.FC<IFormButton> = (props) => (
  <button
    css={tw`flex justify-center text-white font-bold items-center h-auto w-full h-2 bg-purple-600 pl-10 pr-10 pt-6 pb-6 rounded-lg hover:bg-purple-500`}
  >
    {props.isLoading ? (
      <div css={tw`animate-spin`}>
        <SpinnerIcon size="30px" />
      </div>
    ) : (
      props.text
    )}
  </button>
);

// apps/client/src/components/FormButton.vue
<script setup lang="ts">
import SpinnerIcon from "~icons/gg/spinner";
interface IFormButton {
  type?: string;
  loading?: boolean;
}

const props = defineProps<IFormButton>();
</script>

<template>
  <button
    class="w-full ring-0 bg-blue-800 hover:(bg-blue-700) px-6 py-4 text-white transition-all text-sm flex justify-center items-center rounded"
  >
    <spinner-icon v-if="loading" class="animate-spin" />
    <div v-else class="flex flex-row gap-[10px] items-center font-bold">
      <slot name="icon" />
      <slot name="text" />
    </div>
  </button>
</template>
