// apps/client2/src/features/Authentication/pages/login.vue
<script setup lang="ts">
import { useMutation } from 'vue-query'
import InputField from '@/components/InputField.vue'
import FormButton from '@/components/FormButton.vue'
import Alert from '@/components/Alert.vue'
import { useLogin } from '@/features/Authentication/hooks'
import EmailIcon from '~icons/ion/email'
import PasswordIcon from '~icons/ion/key'
import FacebookIcon from '~icons/gg/facebook'
import GoogleIcon from '~icons/gg/google'

const {
  email,
  emailError,
  password,
  passwordError,
  handleSubmit,
  handleReset,
  errorMessage,
  isLoading,
} = useLogin()
</script>

<template>
  <div class="flex flex-row w-full justify-between px-5 py-10 md:px-10">
    <form class="flex flex-col gap-[25px] w-full md:w-[450px]" @submit.prevent="handleSubmit">
      <span class="main-title">Login</span>
      <form-button>
        <template #text>Login with Facebook</template>
        <template #icon>
          <facebook-icon />
        </template>
      </form-button>
      <form-button>
        <template #text>Login with Google</template>
        <template #icon>
          <google-icon />
        </template>
      </form-button>
      <div class="flex flex-row items-center gap-[10px]">
        <div class="h-px w-full bg-gray-600" />
        <div class="text-sm font-light text-blue-600">OR</div>
        <div class="h-px w-full bg-gray-600" />
      </div>
      <alert v-if="errorMessage" variation="alert">{{ errorMessage }}</alert>
      <input-field v-model="email" type="text" :error-message="emailError" placeholder="email">
        <template #icon>
          <email-icon />
        </template>
      </input-field>
      <input-field
        v-model="password"
        type="password"
        :error-message="passwordError"
        placeholder="password"
      >
        <template #icon>
          <password-icon />
        </template>
      </input-field>
      <form-button :loading="isLoading" type="submit">
        <template #text>Login</template>
      </form-button>
    </form>
    <div class="hidden md:block">x</div>
  </div>
</template>

<route lang="yaml">
meta:
  layout: unauthorized
</route>

// apps/client/src/views/Pages/Login/index.tsx
import React from "react";
import {
  FormDivider,
  FormButton,
  SocialLoginButton,
  FormInput,
  FormAlert,
} from "@/components/common";
import { useLogin } from "./useLogin";
import { Link, Redirect } from "wouter";
import { MainContainer } from "@/components/layout";
import { HiOutlineMail as MailIcon } from "react-icons/hi";
import { RiLockPasswordLine as PasswordIcon } from "react-icons/ri";

export const Login = () => {
  const {
    isLoading,
    handleSubmit,
    register,
    formErrors,
    responseError,
    isResponseError,
    isSuccess,
  } = useLogin();

  return (
    <MainContainer>
      {isSuccess && <Redirect to="/" />}
      <div className="flex w-full bg-gray-100">
        <div className="flex h-screen w-full justify-center items-center md:(justify-center w-1/2)">
          <div className="card w-full h-screen md:(w-1/2 min-w-[350px] max-w-[450px] h-auto)">
            <div className="p-10">
              <div className="mb-8 text-4xl font-extrabold text-center header">
                Welcome Back!
              </div>
              <div className="flex gap-[15px] flex-col justify-center">
                <SocialLoginButton variation="google" />
                <SocialLoginButton variation="facebook" />
              </div>
              <div className="flex mt-6 mb-6">
                <FormDivider text="OR" />
              </div>
              <form onSubmit={handleSubmit}>
                <div className="grid grid-flow-row gap-[15px]">
                  {isResponseError && (
                    <FormAlert message={responseError} variation="error" />
                  )}
                  <FormInput
                    {...register("email")}
                    type="email"
                    name="email"
                    placeholder="email"
                    isInvalid={formErrors.email}
                    icon={<MailIcon size="20px" />}
                    errorMessage={formErrors.email?.message}
                  />
                  <FormInput
                    {...register("password")}
                    type="password"
                    name="password"
                    placeholder="password"
                    isInvalid={formErrors?.password}
                    icon={<PasswordIcon size="20px" />}
                    errorMessage={formErrors.password?.message}
                    maxLength={24}
                  />
                  <FormButton isLoading={isLoading} text="Login" />
                </div>
              </form>
            </div>
            <div className="divider md:block"></div>
            <div className="p-10">
              Don't have an account? <Link to="/signup">Signup</Link>
            </div>
          </div>
        </div>
      </div>
    </MainContainer>
  );
};
