// apps/client/src/components/common/FormButton.tsx
import React from "react";
import { ReactComponent as SpinnerIcon } from "@/assets/icons/spinner.svg";

interface IFormButton extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  isLoading?: boolean;
  text?: string;
}

export const FormButton: React.FC<IFormButton> = (props) => (
  <button className="btn-primary justify-center">
    {props.isLoading ? <SpinnerIcon className="animate-spin" /> : props.text}
  </button>
);

// apps/client2/src/components/FormButton.vue
<script setup lang="ts">
import SpinnerIcon from "~icons/gg/spinner";
interface IFormButton {
  type: string;
  loading?: boolean;
}

const props = defineProps<IFormButton>();
</script>

<template>
  <button
    class="
      w-full
      bg-gray-600
      hover:(bg-gray-500)
      px-6
      py-6
      text-white
      transition-all
      text-md
      flex
      justify-center
      items-center
      rounded-full
    "
  >
    <spinner-icon v-if="loading" class="animate-spin" />
    <slot v-else />
  </button>
</template>
