// apps/client/src/views/Login/index.tsx
import React from "react";
import {
  FormDivider,
  FormButton,
  SocialLoginButton,
  FormInput,
  FormAlert,
} from "../../components";
import { useLogin } from "../../hooks";
import { Link, Redirect } from "wouter";
import { MainContainer } from "../../components/layout/MainContainer";
import { HiOutlineMail as MailIcon } from "react-icons/hi";
import { RiLockPasswordLine as PasswordIcon } from "react-icons/ri";

export const Login = () => {
  const {
    isLoading,
    handleSubmit,
    register,
    formErrors,
    responseError,
    isResponseError,
    isSuccess,
  } = useLogin();

  return (
    <MainContainer>
      {isSuccess && <Redirect to="/" />}
      <div className="flex w-full">
        <div className="flex h-screen w-full justify-center items-center md:(justify-center w-1/2)">
          <div className="w-full rounded-lg h-screen p-10 md:(w-1/2 min-w-[350px] max-w-[450px] h-auto) bg-white shadow-2xl">
            <div className="mb-8 text-4xl font-extrabold text-center">
              Welcome Back!
            </div>
            <div className="flex gap-[15px] flex-col justify-center">
                <SocialLoginButton variation="google" />
                <SocialLoginButton variation="facebook" />
            </div>
            <div className="flex mt-6 mb-6">
              <FormDivider text="OR" />
            </div>
            <form onSubmit={handleSubmit}>
              <div className="grid grid-flow-row gap-[15px]">
                {isResponseError && (
                  <FormAlert message={responseError} variation="error" />
                )}
                <FormInput
                  {...register("email")}
                  type="email"
                  name="email"
                  placeholder="email"
                  isInvalid={formErrors.email}
                  icon={<MailIcon size="20px" />}
                  errorMessage={formErrors.email?.message}
                />
                <FormInput
                  {...register("password")}
                  type="password"
                  name="password"
                  placeholder="password"
                  isInvalid={formErrors?.password}
                  icon={<PasswordIcon size="20px" />}
                  errorMessage={formErrors.password?.message}
                  maxLength={24}
                />
                <FormButton isLoading={isLoading} text="Login" />
              </div>
            </form>
            <div className="divider mt-10 -ml-10 -mr-10 md:block"></div>
            <div className="mt-10">
              Don't have an account? <Link to="/signup">Signup</Link>
            </div>
          </div>
        </div>
      </div>
    </MainContainer>
  );
};

// apps/client/src/features/Authentication/pages/login.vue
<script setup lang="ts">
import { useMutation } from "vue-query";
import InputField from "@/components/InputField.vue";
import FormButton from "@/components/FormButton.vue";
import PrimaryButton from "@/components/PrimaryButton.vue";
import Alert from "@/components/Alert.vue";
import { useLogin } from "@/features/Authentication/hooks";
import EmailIcon from "~icons/ion/email";
import PasswordIcon from "~icons/ion/key";
import FacebookIcon from "~icons/gg/facebook";
import GoogleIcon from "~icons/gg/google";

const {
  email,
  emailError,
  password,
  passwordError,
  handleSubmit,
  handleReset,
  errorMessage,
  isLoading,
} = useLogin();
</script>

<template>
  <div class="flex flex-row justify-between w-full">
    <div class="flex flex-col bg-white shadow-lg md:ml-10 w-full md:w-[450px]">
      <form
        class="flex flex-col gap-4 px-5 py-10 md:px-10 rounded-xl"
        @submit.prevent="handleSubmit"
      >
        <span class="text-xl font-bold">Login Now</span>
        <div class="flex flex-row items-center gap-[10px]"></div>
        <alert v-if="errorMessage" variation="error">{{ errorMessage }}</alert>
        <input-field
          v-model="email"
          type="text"
          :error-message="emailError"
          placeholder="email"
          autocomplete="email"
        >
          <template #icon>
            <email-icon />
          </template>
        </input-field>
        <input-field
          v-model="password"
          type="password"
          :error-message="passwordError"
          placeholder="password"
          autocomplete="password"
        >
          <template #icon>
            <password-icon />
          </template>
        </input-field>
        <form-button :loading="isLoading" type="submit">
          <template #text>Login</template>
        </form-button>
      </form>
      <div class="flex flex-row items-center">
        <div class="h-px w-full bg-gray-300" />
        <span class="text-gray-400 text-center text-sm font-bold mx-2">OR</span>
        <div class="h-px w-full bg-gray-300" />
      </div>
      <div class="px-5 py-10 flex flex-col gap-4">
        <primary-button>
          <template #text>Sign in with Google</template>
          <template #icon>
            <google-icon />
          </template>
        </primary-button>
        <primary-button>
          <template #text>Sign in with Facebook</template>
          <template #icon>
            <facebook-icon />
          </template>
        </primary-button>
      </div>
    </div>
  </div>
</template>

<route lang="yaml">
meta:
  layout: unauthorized
</route>
